/**
 * Options to configure request retry behavior
 */
export interface RetryOptions {
  /** Maximum number of retry attempts. Defaults to 0 (no retries). */
  retries?: number;
  /** Initial delay before the first retry in milliseconds. Defaults to 1000. */
  minTimeout?: number;
  /** The multiplier factor to increase retry delay (exponential backoff). Defaults to 2. */
  factor?: number;
}

/**
 * Configuration options for the TMWeasy QR Payment Webhook Client
 */
export interface TMWeasyQRPaymentWebhookConfig {
  /** TMWeasy username */
  username: string;
  /** TMWeasy password */
  password: string;
  /** Connection ID obtained from the TMWeasy settings panel */
  conId: string;
  /**
   * Optional custom API Base URL.
   * Defaults to 'http://tmwallet.thaighost.net/api_pph.php'
   */
  baseUrl?: string;
  /**
   * Optional configuration for automatic retrying when request fails
   */
  retryOptions?: RetryOptions;
}

/**
 * Configuration options for the TMWeasy QR Payment Direct Bank Client
 */
export interface TMWeasyQRPaymentConfig {
  /** TMWeasy username */
  username: string;
  /** TMWeasy password */
  password: string;
  /** Connection ID obtained from the TMWeasy settings panel */
  conId: string;
  /** The accode obtained from banking credentials encoding */
  accode?: string;
  /** The merchant bank account number (exactly 10 digits) */
  accountNo?: string;
  /**
   * Optional custom API Base URL for direct confirmation.
   * Defaults to 'https://tmwallet.thaighost.net/apipp.php'
   */
  baseUrl?: string;
  /**
   * Optional configuration for automatic retrying when request fails
   */
  retryOptions?: RetryOptions;
}

/**
 * Parameters to create a new payment session (Step 1)
 */
export interface CreatePayOptions {
  /**
   * The payment amount. Must be an integer (no decimals).
   * E.g. 50 (for 50 Baht)
   */
  amount: number;
  /**
   * Reference ID of the customer (e.g. username, email, uid, phone number)
   */
  ref1: string;
  /**
   * IP address of the customer making the payment
   */
  ip: string;
}

/**
 * API Response from Create Payment request (Step 1)
 */
export interface CreatePayResponse {
  /** Status of the request: 1 for success, 0 for failure */
  status: 0 | 1;
  /** Payment ID. Required to fetch details in Step 2. Present only if status is 1. */
  id_pay?: string;
  /** Error message. Present only if status is 0. */
  msg?: string;
}

/**
 * PromptPay identifier type:
 * - '01': Mobile Phone Number (e.g. 0812345678)
 * - '02': National ID Card Number (13 digits)
 * - '03': E-Wallet ID (15 digits)
 */
export type PromptPayType = '01' | '02' | '03';

/**
 * Parameters to request payment details and QR code (Step 2)
 */
export interface DetailPayOptions {
  /** The payment ID obtained from Step 1 */
  idPay: string | number;
  /** The PromptPay ID bound to your bank account (Mobile phone number or National ID) */
  promptpayId: string;
  /** The type of PromptPay ID ('01' = phone, '02' = National ID) */
  type: PromptPayType;
}

/**
 * API Response from Get Payment Detail request (Step 2)
 */
export interface DetailPayResponse {
  /** Status of the request: 1 for success, 0 for failure */
  status: 0 | 1;
  /** Customer reference ID (passed as ref1 in Step 1) */
  ref1?: string;
  /**
   * The amount to pay in Satang unit (as a string or number).
   * Divide by 100 to get Baht.
   */
  amount_check?: string;
  /**
   * Helper property added by this SDK: amount_check converted to Baht (float).
   * E.g. 19.01 Baht instead of 1901 Satang.
   */
  amount_baht?: number;
  /** Base64-encoded string of the QR code image */
  qr_image_base64?: string;
  /**
   * Standard EMVCo PromptPay payload calculated by this SDK.
   * Useful for custom client-side QR generation or terminal rendering.
   */
  promptpay_payload?: string;
  /** Remaining time in seconds to complete the payment. Negative value means expired. */
  time_out?: number;
  /** Error message. Present only if status is 0. */
  msg?: string;
}

/**
 * API Response from Cancel Payment request
 */
export interface CancelPayResponse {
  /** Status of the request: 1 for success, 0 for failure */
  status: 0 | 1;
  /** Error or success message */
  msg?: string;
}

/**
 * Webhook raw body POST payload
 */
export interface WebhookPayload {
  /** Payment data string in JSON format */
  data: string;
  /** MD5 signature calculated as md5(data + ":" + api_key) */
  signature: string;
}

/**
 * Structure of the parsed JSON in the webhook's 'data' parameter
 */
export interface WebhookData {
  /** Payment ID generated by TMWeasy */
  id_pay: string;
  /** Customer reference ID passed during creation */
  ref1: string;
  /**
   * The exact amount verified by the bank in Satang unit.
   * E.g. "1901"
   */
  amount_check: string;
  /**
   * The amount in Baht unit as a string.
   * E.g. "19.00"
   */
  amount: string;
  /** Date and time of payment in format "YYYY-MM-DD HH:mm" */
  date_pay: string;
}

/**
 * Enhanced Webhook data parsed and validated by this SDK
 */
export interface ParsedWebhookData extends WebhookData {
  /**
   * Helper property added by this SDK: amount_check converted to Baht as a number.
   * E.g. 19.01
   */
  amount_baht: number;
}

/**
 * Callback options for scheduling automatic payment cancellation
 */
export interface AutoCancelOptions {
  /** Optional callback triggered when the automatic cancellation completes successfully */
  onSuccess?: (response: CancelPayResponse) => void | Promise<void>;
  /** Optional callback triggered when the automatic cancellation fails */
  onError?: (error: Error) => void | Promise<void>;
}

/**
 * Handle returned by scheduleAutoCancel to manage the scheduled cancellation
 */
export interface AutoCancelHandle {
  /** Stops the scheduled cancellation timer immediately. Call this when payment is successful. */
  stop: () => void;
  /** Checks if the cancellation timer has already fired and invoked the cancel request. */
  hasFired: () => boolean;
}

/**
 * Parameters to verify bank direct payment (Step 3)
 */
export interface ConfirmPayOptions {
  /** The payment ID obtained from Step 1 */
  idPay: string | number;
  /** The IP address of the customer making/confirming the transaction */
  ip: string;
  /** The merchant 10-digit bank account number. Optional if pre-configured globally. */
  accountNo?: string;
  /** The bank credentials encoding token (accode). Optional if pre-configured globally. */
  accode?: string;
}

/**
 * API Response from Direct Confirm payment request (Step 3)
 */
export interface ConfirmPayResponse {
  /** Status of the request: 1 for success (paid), 0 for failure/pending */
  status: 0 | 1;
  /** Customer reference ID (passed as ref1 in Step 1) */
  ref1?: string;
  /** The paid amount as a number in Baht (float). */
  amount?: number;
  /** Date and time of payment in format "YYYY-MM-DD HH:mm" if successful */
  date_pay?: string;
  /** Error message. Present only if status is 0. */
  msg?: string;
}
